// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class UserTable_changedForCorrectLogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserTable_changedForCorrectLogin));
        
        string IMigrationMetadata.Id
        {
            get { return "201911191856271_UserTable_changedForCorrectLogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
