// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class password_columnn_deleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(password_columnn_deleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201911231346491_password_columnn_deleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
